FROM        python:3.6.4-slim



RUN         apt-get -y update
RUN         apt-get -y dist-upgrade
RUN         apt-get -y install nginx supervisor
RUN         apt-get -y install build-essential

COPY        .requirements /srv/project/.requirements
WORKDIR     /srv/project
RUN         pip install -r .requirements/dev.txt

ENV         BUILD_MODE             dev
ENV         DJANGO_SETTINGS_MODULE config.settings.dev

COPY        . /srv/project

RUN         cp -f /srv/project/.config/${BUILD_MODE}/nginx.conf     /etc/nginx/nginx.conf &&\
            cp -f /srv/project/.config/${BUILD_MODE}/nginx-app.conf /etc/nginx/sites-available/ &&\
            rm -f /etc/nginx/sites-enabled/* &&\
            ln -sf /etc/nginx/sites-available/nginx-app.conf /etc/nginx/sites-enabled/

RUN         cp /srv/project/.config/${BUILD_MODE}/supervisord.conf /etc/supervisor/conf.d/


#WORKDIR      /srv/project/app
#RUN         export DJANGO_SETTINGS_MODULE=config.settings.dev && python manage.py migrate && python manage.py createsu

CMD         pkill nginx; supervisord -n




